Document: mecab-ipadic-neologd
Title: Debian mecab-ipadic-neologd Manual
Author: <insert document author here>
Abstract: This manual describes what mecab-ipadic-neologd is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/mecab-ipadic-neologd/mecab-ipadic-neologd.sgml.gz

Format: postscript
Files: /usr/share/doc/mecab-ipadic-neologd/mecab-ipadic-neologd.ps.gz

Format: text
Files: /usr/share/doc/mecab-ipadic-neologd/mecab-ipadic-neologd.text.gz

Format: HTML
Index: /usr/share/doc/mecab-ipadic-neologd/html/index.html
Files: /usr/share/doc/mecab-ipadic-neologd/html/*.html
